#pragma once

#include "CoreMinimal.h"

#define UE_COLLISION_PROFILE_EVENTTRIGGER TEXT("EventTrigger")
#define UE_COLLISION_PROFILE_PLAYER TEXT("Player")
#define UE_COLLISION_PROFILE_PLAYERATTACK TEXT("PlayerAttack")
#define UE_COLLISION_PROFILE_ENEMY TEXT("Enemy")
#define UE_COLLISION_PROFILE_BOSSARMOR TEXT("BossArmor")
#define UE_COLLISION_PROFILE_RAGDOLL TEXT("Ragdoll")
#define UE_COLLISION_PROFILE_ENEMYHEADHIT TEXT("EnemyHeadHit")
#define UE_COLLISION_PROFILE_ENEMYWEAKHIT TEXT("EnemyWeakHit")
#define UE_COLLISION_PROFILE_ENEMYATTACK TEXT("EnemyAttack")
#define UE_COLLISION_PROFILE_ENEMYBULLET TEXT("EnemyBullet")